name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.YOUR_SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.YOUR_SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Function to Supabase
        run: supabase functions deploy --project-ref $PROJECT_ID
        env:
          SUPABASE_ACCESS_TOKEN: $SUPABASE_ACCESS_TOKEN
          PROJECT_ID: $PROJECT_ID