name: Deploy Function and Push Schema Changes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup_and_deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }} # Make sure to replace <project-id> with your actual project ID

    steps:
      # Setup Supabase CLI
      - uses: actions/checkout@v3
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Initialize Supabase
      - name: Initialize Supabase
        run: supabase init